spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
#      jdbc-url: jdbc:mysql://3.39.94.151:3306/batch_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      jdbc-url: jdbc:mysql://localhost:3306/batch_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
      username: sa
#      password: infra1122!
      password: 1234
  batch:
    initialize-schema: never
    job:
      names: ${job.name:NONE}